ALTER SESSION SET CURRENT_SCHEMA=DTVLA;

DECLARE

BEGIN

	insert into DVM_SISTEMA (ID,NOMBRE,DESCRIPCION) values  ( 1,'COUNTRY','Tabla Country');
insert into DVM_SISTEMA (PAIS,ID,NOMBRE,DESCRIPCION) values  ( 'PE',2,'MR23','IBS MR23');
update DVM_ENTIDAD_CANONICA set (2,'FINANCIAL_ACCOUNT_TYPE','Tabla Financial_account_typeNNN') where ID = 2 and NOMBRE = 'FINANCIAL_ACCOUNT_TYPE' and DESCRIPCION = 'Tabla Financial_account_typeNNN';
insert into DVM_ENTIDAD_CANONICA (ID,NOMBRE,DESCRIPCION) values  ( 4,'METHOD_OF_PAYMENT','Tabla Method_of_payment');
update DVM_VALOR_CANONICO set (142,2,'C','C') where ID = 142 and ID_ENTIDAD_CANONICA = 2 and VALOR_CANONICO = 'C' and DESCRIPCION = 'C';
update DVM_VALOR_CANONICO set (66,2,'E','E') where ID = 66 and ID_ENTIDAD_CANONICA = 2 and VALOR_CANONICO = 'E' and DESCRIPCION = 'E';
update DVM_VALOR_CANONICO set (67,2,'M','M') where ID = 67 and ID_ENTIDAD_CANONICA = 2 and VALOR_CANONICO = 'M' and DESCRIPCION = 'M';
update DVM_VALOR_CANONICO set (77,4,'K','K') where ID = 77 and ID_ENTIDAD_CANONICA = 4 and VALOR_CANONICO = 'K' and DESCRIPCION = 'K';
update DVM_VALOR_CANONICO set (97,4,'F','F') where ID = 97 and ID_ENTIDAD_CANONICA = 4 and VALOR_CANONICO = 'F' and DESCRIPCION = 'F';
update DVM_VALOR_CANONICO set (98,4,'F','F') where ID = 98 and ID_ENTIDAD_CANONICA = 4 and VALOR_CANONICO = 'F' and DESCRIPCION = 'F';
insert into DVM_VALOR_SISTEMA (ID,ID_SISTEMA,VALOR_SISTEMA,ID_VALOR_CANONICO,ID_ENTIDAD_CANONICA) values  ( 142,23,'1',6,2);
insert into DVM_VALOR_SISTEMA (ID,ID_SISTEMA,VALOR_SISTEMA,ID_VALOR_CANONICO,ID_ENTIDAD_CANONICA) values  ( 154,2,'71',79,4);
insert into DVM_VALOR_SISTEMA (ID,ID_SISTEMA,VALOR_SISTEMA,ID_VALOR_CANONICO,ID_ENTIDAD_CANONICA,DESCRIPCION) values  ( 155,2,'72',77,4,'');
insert into DVM_VALOR_SISTEMA (ID,ID_SISTEMA,VALOR_SISTEMA,ID_VALOR_CANONICO,ID_ENTIDAD_CANONICA) values  ( 160,2,'77',71,4);
insert into DVM_VALOR_SISTEMA (ID,ID_SISTEMA,VALOR_SISTEMA,ID_VALOR_CANONICO,ID_ENTIDAD_CANONICA) values  ( 158,2,'75',87,4);
insert into DVM_VALOR_SISTEMA (ID,ID_SISTEMA,VALOR_SISTEMA,ID_VALOR_CANONICO,ID_ENTIDAD_CANONICA) values  ( 159,2,'72',82,4);

	
	COMMIT;
		DBMS_OUTPUT.Put_line ('Termino OK');
	EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.Put_line ('No se realizo ningun Insert.Error: ' || SQLERRM);

END;