ALTER SESSION SET CURRENT_SCHEMA=DTVLA;

DECLARE

valorcanonico142 DTVLA.DVM_VALOR_CANONICO.ID%type;


BEGIN

	update DVM_SISTEMA set (PAIS = 'CL',DESCRIPCION = 'IBS MR23') where NOMBRE = 'MR23';
	
	select nvl(max(id),0)+1 into valorcanonico142 from DTVLA.DVM_VALOR_CANONICO;
	insert into DVM_VALOR_CANONICO (ID, ID_ENTIDAD_CANONICA, VALOR_CANONICO, DESCRIPCION) values  (valorcanonico142,  4, 'C', 'CXX');
	update DVM_VALOR_SISTEMA set (VALOR_SISTEMA = '1') where ID_SISTEMA = 2 and ID_VALOR_CANONICO = 115 and ID_ENTIDAD_CANONICA = 3;
	update DVM_VALOR_SISTEMA set (VALOR_SISTEMA = '4') where ID_SISTEMA = 2 and ID_VALOR_CANONICO = 119 and ID_ENTIDAD_CANONICA = 3;
	update DVM_VALOR_SISTEMA set (VALOR_SISTEMA = 'XXU') where ID_SISTEMA = 1 and ID_ENTIDAD_CANONICA = 1 and ID_VALOR_CANONICO = 4;

	
	COMMIT;
		DBMS_OUTPUT.Put_line ('Termino OK');
	EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.Put_line ('No se realizo ningun Insert.Error: ' || SQLERRM);

END;